server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: security-route
          uri: lb://security
          predicates:
            - Path=/auth/**

        - id: task-route
          uri: lb://service-task
          predicates:
            - Path=/task/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoint:
    gateway:
      enabled: true
