spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5433/task_data
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update